[workspace]
resolver = "3"
members = [
    "crates/kernel",
    "crates/macros",
    "crates/tests",
    "crates/uji",
    "lua",
]

[workspace.package]
version = "0.2.2"
edition = "2024"
rust-version = "1.88"
license = "GPL-3.0-or-later"
authors = ["dracarys18"]
repository = "https://github.com/uji-labs/uji"

[workspace.lints.rust]
unsafe_code = "deny"
rust_2018_idioms = { level = "deny", priority = -1 }
unreachable_pub = "deny"
unused_qualifications = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unused_lifetimes = "deny"
unused_macro_rules = "deny"
macro_use_extern_crate = "deny"
non_ascii_idents = "deny"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
redundant_clone = "deny"
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
unwrap_used = "deny"
expect_used = "deny"
panic = "deny"
todo = "deny"
dbg_macro = "deny"
unimplemented = "deny"
unwrap_in_result = "deny"
exit = "deny"
mem_forget = "deny"
float_cmp = "deny"
lossy_float_literal = "deny"
mutex_atomic = "deny"
rc_buffer = "deny"
clone_on_ref_ptr = "deny"
verbose_file_reads = "deny"
same_name_method = "deny"
empty_structs_with_brackets = "deny"
try_err = "deny"
unneeded_field_pattern = "deny"
large_stack_arrays = "deny"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
