[package]
name = "uji-lua"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "The Lua that makes up uji"
build = "build.rs"
include = ["Cargo.toml", "build.rs", "lib.rs", "uji/**/*.lua"]

[lib]
path = "lib.rs"

[lints]
workspace = true
