[package]
name = "uji-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false
build = "../uji/build.rs"

[[bin]]
name = "uji-test"
path = "src/bin/uji-test.rs"

[dependencies]
uji-kernel = { path = "../kernel" }
uji-lua = { path = "../../lua" }

[lints]
workspace = true
