local Composer = require("uji.core.ui.composer")
local Line = require("uji.core.ui.line")

local function typed(text)
    local line = Line()
    line:set(text)
    return line
end

local function pasted(count)
    local lines = {}
    for at = 0, count - 1 do
        lines[#lines + 1] = "line " .. at
    end
    return table.concat(lines, "\n")
end

describe("a line", function()
    it("deletes one word at a time", function()
        local line = typed("cargo run --release")
        line:delete_word_back()
        assert.equal("cargo run ", line.text)
        line:delete_word_back()
        assert.equal("cargo ", line.text)
        local path = typed("open crates/ui/src")
        path:delete_word_back()
        assert.equal("open ", path.text, "a path is one word")
    end)

    it("stops a word motion where a word starts", function()
        local line = typed("one two_three four")
        line:home()
        line:word_right()
        assert.equal(3, line.cursor)
        line:word_right()
        assert.equal(13, line.cursor, "an underscore joins a word")
        line:word_left()
        assert.equal(4, line.cursor)
        local punctuated = typed("one ... two")
        punctuated:word_left()
        assert.equal(8, punctuated.cursor, "separators are skipped first")
        punctuated:word_left()
        assert.equal(0, punctuated.cursor)
    end)

    it("yanks a kill back", function()
        local line = typed("hello world")
        line:home()
        for _ = 1, 5 do
            line:right()
        end
        line:delete_to_start()
        assert.equal(" world", line.text)
        line:tail()
        line:yank()
        assert.equal(" worldhello", line.text)
    end)

    it("stops a kill to the end at the newline", function()
        local line = typed("first\nsecond")
        line:home()
        line:up()
        line:right()
        line:right()
        line:delete_to_end()
        assert.equal("fi\nsecond", line.text)
    end)

    it("moves a multi-line draft by line and keeps its column", function()
        local line = typed("abcd\nefgh")
        line:home()
        line:right()
        line:right()
        assert.equal(7, line.cursor, "column 2 of the second line")
        assert.is_true(line:up())
        assert.equal(2, line.cursor)
        assert.is_true(line:down())
        assert.equal(7, line.cursor)
        local shorter = typed("ab\nlonger")
        assert.is_true(shorter:up())
        assert.equal(2, shorter.cursor, "clamped to the shorter line")
        local single = typed("only one line")
        assert.is_not_true(single:up())
        assert.is_not_true(single:down())
    end)

    it("keeps home and end on the line the cursor is on", function()
        local line = typed("first\nsecond")
        line:home()
        assert.equal(6, line.cursor)
        line:tail()
        assert.equal(12, line.cursor)
    end)

    it("edits on character boundaries", function()
        local line = typed("héllo wörld")
        line:delete_word_back()
        assert.equal("héllo ", line.text)
        line:backspace()
        assert.equal("héllo", line.text)
        line:left()
        line:left()
        line:left()
        line:backspace()
        assert.equal("hllo", line.text)
    end)

    it("does not count moving the cursor as an edit", function()
        local line = typed("text")
        line:home()
        local revision = line.revision
        line:right()
        line:word_right()
        line:tail()
        assert.equal(revision, line.revision)
        line:insert("!")
        assert.are_not.equal(revision, line.revision)
    end)
end)

describe("a composer", function()
    it("shows a paste as one marker that expands when it is sent", function()
        local composer = Composer()
        composer:paste(pasted(5))
        assert.equal("[paste #1", composer:text():sub(1, 9))
        assert.equal(pasted(5), composer:take())
    end)

    it("takes a whole paste marker with backspace", function()
        local composer = Composer()
        composer:paste(pasted(5))
        composer:backspace()
        assert.equal("", composer:text())
    end)

    it("does not expand a half deleted paste marker", function()
        local composer = Composer()
        composer:edit(function(line)
            line:insert("x")
        end)
        composer:paste(pasted(5))
        composer:edit(Line.delete_word_back)
        assert.is_nil(composer:take():find("line 0", 1, true), "expanded a marker that was partly deleted")
    end)

    it("continues the line after a trailing backslash", function()
        local composer = Composer()
        composer:set("first \\")
        assert.is_true(composer:continue_line())
        assert.equal("first \n", composer:text())
        assert.is_not_true(composer:continue_line())
    end)

    it("comes back to the draft after history recall", function()
        local composer = Composer()
        composer:set("draft")
        local history = { [0] = "newest", [1] = "older" }
        local function lookup(back)
            return history[back]
        end
        assert.is_true(composer:recall_prev(lookup))
        assert.equal("newest", composer:text())
        assert.is_true(composer:recall_prev(lookup))
        assert.equal("older", composer:text())
        assert.is_true(composer:recall_next(lookup))
        assert.is_true(composer:recall_next(lookup))
        assert.equal("draft", composer:text())
    end)
end)
