[package]
name = "libuji"
version.workspace = true
edition.workspace = true

[dependencies]
uji-core = { path = "../core" }
uji-api = { path = "../api" }
uji-cmd = { path = "../cmd" }
tui = { path = "../tui" }
calloop = "0.14.4"
crossterm = "0.29"
mlua = { version = "0.12", features = ["lua54", "vendored"] }
notify = "8.1"
thiserror = "2"

[lints]
workspace = true
