local ito = require("ito")
local tables = require("uji.core.tables")

local COLORS = {
    text = ito.rgb(0xd4d4d4),
    muted = ito.rgb(0x808080),
    code = ito.rgb(0xe0af68),
    accent = ito.Color.cyan,
    user_bg = ito.rgb(0x343541),
    selected_bg = ito.rgb(0x3a3a4a),
    cursor = ito.Color.white,
    error = ito.Color.red,
    notice = ito.Color.red,
    syntax = {
        keyword = ito.Color.cyan,
        string = ito.rgb(0xe0af68),
        number = ito.rgb(0xe0af68),
        comment = ito.rgb(0x808080),
        func = ito.rgb(0xdcdcaa),
        type = ito.rgb(0x4ec9b0),
        constant = ito.rgb(0x569cd6),
    },
    call = {
        done = ito.rgb(0x87d787),
    },
    diff = {
        added = ito.rgb(0x5fd75f),
        removed = ito.rgb(0xd75f5f),
        added_bg = ito.rgb(0x005f00),
        removed_bg = ito.rgb(0x5f0000),
        added_word_bg = ito.rgb(0x008700),
        removed_word_bg = ito.rgb(0x870000),
    },
}

local function styles(c)
    local S = ito.TextStyle
    return {
        plain = S({}),
        screen = S({ background = c.background }),
        text = S({ foreground = c.text }),
        bold = S({ foreground = c.text, bold = true }),
        muted = S({ foreground = c.muted }),
        dim = S({ foreground = c.muted, dim = true }),
        faint = S({ foreground = c.muted, italic = true, dim = true }),
        system = S({ foreground = c.muted, italic = true }),
        code = S({ foreground = c.code }),
        accent = S({ foreground = c.accent, bold = true }),
        highlight = S({ foreground = c.accent }),
        user = S({ foreground = c.text, background = c.user_bg }),
        selected = S({ background = c.selected_bg }),
        chosen = S({ foreground = c.text, background = c.selected_bg }),
        chosen_name = S({ foreground = c.accent, background = c.selected_bg }),
        chosen_desc = S({ foreground = c.muted, background = c.selected_bg }),
        error = S({ foreground = c.error }),
        notice = S({ foreground = c.notice }),
        cursor = S({ foreground = c.cursor, blink = true }),
        input = S({ foreground = c.text }),
        border = S({ foreground = c.muted }),
        reverse = S({ reverse = true }),
        confirm_title = S({ foreground = c.text, bold = true }),
        confirm_body = S({ foreground = c.text }),
        confirm_selected = S({ foreground = c.accent, bold = true }),
        confirm_unselected = S({ foreground = c.muted }),
        heading1 = S({ foreground = c.accent, bold = true }),
        heading2 = S({ foreground = c.accent, bold = true }),
        heading3 = S({ foreground = c.text, bold = true }),
        heading4 = S({ foreground = c.text, bold = true }),
        heading5 = S({ foreground = c.text, bold = true }),
        heading6 = S({ foreground = c.text, bold = true }),
        strong = S({ bold = true }),
        emphasis = S({ italic = true }),
        strikethrough = S({ strikethrough = true }),
        link = S({ foreground = c.link, underline = true }),
        table_head = S({ bold = true }),
        selection = S({ reverse = true }),
        syntax = {
            keyword = S({ foreground = c.syntax.keyword }),
            string = S({ foreground = c.syntax.string }),
            number = S({ foreground = c.syntax.number }),
            comment = S({ foreground = c.syntax.comment, italic = true }),
            func = S({ foreground = c.syntax.func }),
            type = S({ foreground = c.syntax.type }),
            constant = S({ foreground = c.syntax.constant }),
        },
        call = {
            label = S({ foreground = c.text, bold = true }),
            detail = S({ foreground = c.text }),
            running = S({ foreground = c.muted }),
            done = S({ foreground = c.call.done }),
            failed = S({ foreground = c.error }),
        },
        diff = {
            added = S({ background = c.diff.added_bg }),
            removed = S({ foreground = c.text, background = c.diff.removed_bg }),
            added_sign = S({ foreground = c.diff.added, background = c.diff.added_bg }),
            removed_sign = S({ foreground = c.diff.removed, background = c.diff.removed_bg }),
            added_word = S({ background = c.diff.added_word_bg }),
            removed_word = S({ background = c.diff.removed_word_bg }),
        },
    }
end

local SYMBOLS = {
    spinner = { "⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏" },
    tool = "⏺",
    branch = "⎿",
    more = "…",
    shell = "!",
    rule = "─",
    notice = "!",
    thinking = "│",
    queued = "›",
    running = "⋯",
    jump = "↓",
    bullets = { "•", "◦", "▪" },
    quote = "│",
    column = "│",
    task_done = "[x]",
    task_open = "[ ]",
    cursor = "█",
    input = "",
    mask = "•",
    pointer = "›",
    prompt = ">",
}

local BORDERS = {
    plain = {
        top_left = "┌",
        top_right = "┐",
        bottom_left = "└",
        bottom_right = "┘",
        horizontal = "─",
        vertical = "│",
    },
    rounded = {
        top_left = "╭",
        top_right = "╮",
        bottom_left = "╰",
        bottom_right = "╯",
        horizontal = "─",
        vertical = "│",
    },
}

local TEXT = {
    confirm_yes = "Yes",
    confirm_no = "No",
    confirm_allow = "proceed",
    confirm_deny = "and tell uji what to do differently",
    exit = "exit",
    compacted = "compacted",
    hidden = "+%d lines",
    jump = "Jump to bottom",
    ordered = "%d.",
    current = "(current)",
    range = "%d–%d of %d",
    scroll = "lines %d-%d of %d, scroll for more",
    sessions_title = "Sessions in %s",
    sessions_empty = "No sessions in current directory",
    column_title = "TITLE",
    column_updated = "UPDATED",
    column_id = "ID",
    key_move = "↑/↓",
    key_open = "enter",
    key_quit = "esc",
    navigate = "navigate",
    resume = "resume",
    quit = "quit",
    working = "Working (%ds)",
    job = "job %d",
    added = "Added %d %s",
    removed = "removed %d %s",
    line = "line",
    lines = "lines",
    copied = "copied %d line(s)",
    copied_terminal = "copied %d line(s) via the terminal",
    pasted_lines = "[paste #%d +%d lines]",
    pasted_chars = "[paste #%d %d chars]",
    image = "[image #%d]",
}

local LIMITS = {
    spinner_interval = 0.08,
    suggest_rows = 5,
    tool_preview = 8,
    diff_preview = 20,
    diff_context = 3,
    argument_preview = 200,
    message_gap = 1,
    section_gap = 1,
    bottom_gap = 1,
    indent = 2,
    rule_width = 60,
    block_gap = 1,
    reply_margin = 1,
    input_rows = 10,
    select_rows = 13,
    suggest_name = 12,
    preview_min = 24,
    sessions_updated = 14,
    sessions_id = 36,
    float_width = 90,
    float_height = 80,
    flash = 1,
    paste_lines = 1,
    paste_chars = 80,
}

return function(changes)
    changes = changes or {}
    local colors = tables.merged(COLORS, changes.colors)
    local extra = type(changes.styles) == "function" and changes.styles(colors) or changes.styles
    return {
        name = changes.name or "default",
        colors = colors,
        styles = tables.merged(styles(colors), extra),
        symbols = tables.merged(SYMBOLS, changes.symbols),
        borders = tables.merged(BORDERS, changes.borders),
        text = tables.merged(TEXT, changes.text),
        limits = tables.merged(LIMITS, changes.limits),
        options = tables.merged({}, changes.options),
        views = tables.merged({}, changes.views),
    }
end
